'use strict';
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const source = fs.readFileSync(path.join(__dirname,'../assets/js/site.js'),'utf8');
function element(value='') { return {value,textContent:'',hidden:false,handlers:{},addEventListener(type,fn){this.handlers[type]=fn},replaceChildren(...children){this.textContent=children.map(c=>c.textContent).join('\n')}}; }
const els = Object.fromEntries(['site-search','search-status','url-tool','url-input','url-output','odds-tool','odds-input','amount-input','odds-output'].map(k=>['#'+k,element()]));
const cards=['سیب بت؛ راهنمای بررسی حساب','هات بت؛ بررسی دامنه','راهنمای الگوریتم'].map(t=>Object.assign(element(),{textContent:t}));
const document={querySelector:s=>els[s]||null,querySelectorAll:()=>cards,createElement:()=>element()};
vm.runInNewContext(source,{document,URL,Error,Number,console});
els['#site-search'].value='سيب بت'; els['#site-search'].handlers.input();
assert.equal(cards[0].hidden,false);assert.equal(cards[1].hidden,true);
els['#site-search'].value='چیزی ناموجود';els['#site-search'].handlers.input();assert(cards.every(c=>c.hidden));
els['#site-search'].value='';els['#site-search'].handlers.input();assert(cards.every(c=>!c.hidden));
const submit=id=>els[id].handlers.submit({preventDefault(){}});
els['#url-input'].value='https://example.com.evil.test/help';submit('#url-tool');
assert(els['#url-output'].textContent.includes('example.com.evil.test'));
els['#url-input'].value='https://example.com@evil.test/help';submit('#url-tool');
assert(els['#url-output'].textContent.includes('نام میزبان: evil.test'));
assert(els['#url-output'].textContent.includes('قبل از @'));
els['#url-input'].value='javascript:alert(1)';submit('#url-tool');assert(els['#url-output'].textContent.includes('https://'));
els['#url-input'].value='http://example.com/<img>';submit('#url-tool');assert(els['#url-output'].textContent.includes('HTTPS ندارد'));
els['#url-input'].value='https://xn--e1afmkfd.xn--p1ai/';submit('#url-tool');assert(els['#url-output'].textContent.includes('بین‌المللی'));
els['#odds-input'].value='2.5';els['#amount-input'].value='100';submit('#odds-tool');
assert(els['#odds-output'].textContent.includes('۲۵۰'));assert(els['#odds-output'].textContent.includes('۴۰'));
els['#odds-input'].value='1';submit('#odds-tool');assert(els['#odds-output'].textContent.includes('بیشتر از ۱'));
els['#odds-input'].value='1e308';els['#amount-input'].value='1e308';submit('#odds-tool');assert(els['#odds-output'].textContent.includes('بیشتر از ۱'));
assert(!/innerHTML|fetch\(|XMLHttpRequest|localStorage|document\.cookie/.test(source),'Unexpected HTML injection or data transmission/storage');
console.log('PASS: Persian/Arabic search, empty search, deceptive URL parsing, credentials, protocols, international domains, odds math and invalid/overflow inputs.');
